<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            Admin\Handler\DashboardHandler::class => Admin\Handler\DashboardHandlerFactory::class,
            Admin\Handler\DeletePostHandler::class => Admin\Handler\DeletePostHandlerFactory::class,
            Admin\Handler\PostListHandler::class => Admin\Handler\PostListHandlerFactory::class,
            Admin\Handler\PostUploadHandler::class => Admin\Handler\PostUploadHandlerFactory::class,
            App\Handler\AccountHandler::class => App\Handler\AccountHandlerFactory::class,
            App\Handler\MainPageHandler::class => App\Handler\MainPageHandlerFactory::class,
            App\Handler\PostPageHandler::class => App\Handler\PostPageHandlerFactory::class,
            Authorization\Handler\LoginHandler::class => Authorization\Handler\LoginHandlerFactory::class,
            Authorization\Handler\LogoutHandler::class => Authorization\Handler\LogoutHandlerFactory::class,
            Authorization\Handler\RegistrationHandler::class => Authorization\Handler\RegistrationHandlerFactory::class,
            admin\Handler\DashboardHandler::class => admin\Handler\DashboardHandlerFactory::class,
        ],
    ],
];
